const floridaCities = ["Jacksonville",
"Miami",
"Tampa",
"Orlando",
"St. Petersburg",
"Hialeah",
"Tallahassee",
"Fort Lauderdale",
"Port St. Lucie",
"Cape Coral",
"Pembroke Pines",
"Hollywood",
"Miramar",
"Gainesville",
"Coral Springs",
"Miami Gardens",
"Clearwater",
"Palm Bay",
"Pompano Beach",
"West Palm Beach",
"Lakeland",
"Davie",
"Miami Beach",
"Sunrise",
"Plantation",
"Boca Raton",
"Deltona",
"Largo",
"Deerfield Beach",
"Palm Coast",
"Melbourne",
"Boynton Beach",
"Lauderhill",
"Weston",
"Fort Myers",
"Kissimmee",
"Homestead",
"Tamarac",
"Delray Beach",
"Daytona Beach",
"North Miami",
"Wellington",
"North Port",
"Jupiter",
"Ocala",
"Port Orange",
"Margate",
"Coconut Creek",
"Sanford",
"Sarasota",
"Pensacola",
"Bradenton",
"Palm Beach Gardens",
"Pinellas Park",
"Coral Gables",
"Doral",
"Bonita Springs",
"Apopka",
"Titusville",
"North Miami Beach",
"Oakland Park",
"Fort Pierce",
"North Lauderdale",
"Cutler Bay",
"Altamonte Springs",
"St. Cloud",
"Greenacres",
"Ormond Beach",
"Ocoee",
"Hallandale Beach",
"Winter Garden",
"Aventura"]

export default floridaCities